services:
  mongodb:
    image: mongo:8
    container_name: gestor_opiniones_mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - gestor_opiniones_data:/data/db

volumes:
  gestor_opiniones_data:
